/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./components/Container.vue')['default']
    EntryList: typeof import('./components/EntryList.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RadioGroup: typeof import('./components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./components/SearchBox.vue')['default']
  }
}
